AtivMod3JoaoLucas/AtivMod3JoaoLucas/Models/Destino.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace AgenciaViagens.Models
{
    public class Destino
    {
        [Key]
        public int Id { get; set; }

        [Required]
        public string Partida { get; set; }

        [Required]
        public string Chegada { get; set; }

        [Required]
        public string Ida { get; set; }

        [Required]
        public string Volta { get; set; }
    }
}

AtivMod3JoaoLucas/AtivMod3JoaoLucas/Models/ErrorViewModel.cs
using System;

namespace AgenciaViagens.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AtivMod3JoaoLucas/AtivMod3JoaoLucas/Models/Usuario.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace AgenciaViagens.Models
{
    public class Usuario
    {
        [Key]
        public int Id { get; set; }

        [Required]
        public string Nome { get; set; }

        [Required]
        public int Idade { get; set; }

        [Required]
        public string Email { get; set; }

        [Required]
        public string Telefone { get; set; }
    }
}

AtivMod3JoaoLucas/AtivMod3JoaoLucas/Controllers/ContaController.cs
using AgenciaViagens.Data;
using AgenciaViagens.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AgenciaViagens.Controllers
{
    public class ContaController : Controller 
    {
        private readonly ContaContext _context;

        public ContaController(ContaContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            IEnumerable<Usuario> ListaUsuario = _context.Usuarios;
            return View(ListaUsuario);
        }

        public IActionResult Destinos()
        {
            return View();
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Usuario novoUsuario)
        {
            if (ModelState.IsValid)
            {
                _context.Usuarios.Add(novoUsuario);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }

            return View();
        }

        public IActionResult EditarUsuario(int id)
        {
            var nomeUsuario = _context.Usuarios.Find(id);
            if (nomeUsuario == null)
            {
                return RedirectToAction("Index");
            }
            return View(nomeUsuario);
        }

        [HttpPost]
        public IActionResult EditarUsuario(Usuario novoUsuario)
        {
            _context.Usuarios.Update(novoUsuario);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult DeletarUsuario(int id)
        {
            var nomeUsuario = _context.Usuarios.Find(id);
            _context.Usuarios.Remove(nomeUsuario);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

AtivMod3JoaoLucas/AtivMod3JoaoLucas/Controllers/DestinoController.cs
using AgenciaViagens.Data;
using AgenciaViagens.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AgenciaViagens.Controllers
{
    public class DestinoController : Controller 
    {
        private readonly ContaContext _context;

        public DestinoController(ContaContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            IEnumerable<Destino> ListaDestino = _context.Destinos;
            return View(ListaDestino);
        }

        public IActionResult Destinos()
        {
            return View();
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Destino novoDestino)
        {
            if (ModelState.IsValid)
            {
                _context.Destinos.Add(novoDestino);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }

            return View();
        }

        public IActionResult EditarDestino(int id)
        {
            var nomeDestino = _context.Destinos.Find(id);
            if (nomeDestino == null)
            {
                return RedirectToAction("Index");
            }
            return View(nomeDestino);
        }

        [HttpPost]
        public IActionResult EditarDestino(Destino novoDestino)
        {
            _context.Destinos.Update(novoDestino);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult DeletarDestino(int id)
        {
            var nomeDestino = _context.Destinos.Find(id);
            _context.Destinos.Remove(nomeDestino);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

AtivMod3JoaoLucas/AtivMod3JoaoLucas/Controllers/HomeController.cs
using AgenciaViagens.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace AgenciaViagens.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public IActionResult Promocoes()
        {
            return View();
        }

        public IActionResult Contato()
        {
            return View();
        }
    }
}

AtivMod3JoaoLucas/AtivMod3JoaoLucas/Views/Conta/Create.cshtml
@model AgenciaViagens.Models.Usuario;

@{
    ViewData["Title"] = "Novo Usuario";
}
<br />
<br />
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <h3>Cadastrar Novo Usuario</h3>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-sm-10">
            <form method="post" asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Nome" class="control-label">Nome</label>
                    <input asp-for="Nome" class="form-control" />
                    <span asp-validation-for="Nome" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Idade" class="control-label">Idade</label>
                    <input asp-for="Idade" class="form-control" />
                    <span asp-validation-for="Idade" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Email" class="control-label">E-mail</label>
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Telefone" class="control-label">Telefone (somente números)</label>
                    <input asp-for="Telefone" class="form-control" />
                    <span asp-validation-for="Telefone" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Criar Usuário" class="btn btn-warning" />
                </div>
            </form>
        </div>
    </div>
</div>

AtivMod3JoaoLucas/AtivMod3JoaoLucas/Views/Conta/EditarUsuario.cshtml
@model AgenciaViagens.Models.Usuario;

@{
    ViewData["Title"] = "Atualizar dados";
}
<br />
<br />
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <h3>Atualizar dados do usuário</h3>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-sm-10">
            <form method="post" asp-action="EditarUsuario">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Nome" class="control-label">Nome</label>
                    <input asp-for="Nome" class="form-control" />
                    <span asp-validation-for="Nome" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Idade" class="control-label">Idade</label>
                    <input asp-for="Idade" class="form-control" />
                    <span asp-validation-for="Idade" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Email" class="control-label">E-mail</label>
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Telefone" class="control-label">Telefone (somente números)</label>
                    <input asp-for="Telefone" class="form-control" />
                    <span asp-validation-for="Telefone" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Atualizar" class="btn btn-warning" />
                </div>
            </form>
        </div>
    </div>
</div>

AtivMod3JoaoLucas/AtivMod3JoaoLucas/Views/Conta/Index.cshtml
@model IEnumerable<AgenciaViagens.Models.Usuario> 
    @{
        ViewData["Title"] = "Lista de Usuários";
}
<br />
<br />
                      <div class="container">
                          <div class="row">
                              <div class="col-sm-6">
                                  <h3>Lista de Usuarios</h3>
                              </div>
                              <div class="col-sm-6">
                                  <a class="btn btn-warning d-block" asp-action="Create" asp-controller="Conta">Cadastro de Titular e Acompanhantes</a>
                              </div>
                          </div>
                          <br />
                          <br />
                          <div class="row">
                              @if (Model.Count() > 0)
                              {
                              <table class="table table-bordered table-striped">
                                  <thead>
                                      <tr>
                                          <td>@Html.DisplayNameFor(m => m.Id)</td>
                                          <td>@Html.DisplayNameFor(m => m.Nome)</td>
                                          <td>@Html.DisplayNameFor(m => m.Idade)</td>
                                          <td>@Html.DisplayNameFor(m => m.Email)</td>
                                          <td>@Html.DisplayNameFor(m => m.Telefone)</td>
                                          <td>Ações</td>
                                      </tr>
                                  </thead>
                                  <tbody>
                                      @foreach (var item in Model)
                                      {
                                      <tr>
                                          <td>@item.Id</td>
                                          <td>@item.Nome</td>
                                          <td>@item.Idade</td>
                                          <td>@item.Email</td>
                                          <td>@item.Telefone</td>
                                          <td>
                                              <a asp-action="EditarUsuario" asp-route-id="@item.Id" class="btn text-danger">Editar</a>
                                              <a asp-action="DeletarUsuario" asp-route-id="@item.Id" class="btn btn-danger">Deletar</a>
                                          </td>
                                      </tr>

                                      }
                                  </tbody>
                              </table>
                              }
                              else
                              {
                              <p>Sem registros.</p>
                              }
                          </div>
                      </div>

AtivMod3JoaoLucas/AtivMod3JoaoLucas/Views/Contato/Index.cshtml
@{
    ViewData["Title"] = "Pomocoes";
}
<h1>@ViewData["Title"]</h1>

<p>Use this page to detail your site's privacy policy.</p>

AtivMod3JoaoLucas/AtivMod3JoaoLucas/Views/Destino/Create.cshtml
@model AgenciaViagens.Models.Destino;

@{
    ViewData["Title"] = "Novo Usuario";
}
<br />
<br />
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <h3>Para onde quer viajar?</h3>
            <h6>Preencha os dados da viagem corretamente</h6>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-sm-10">
            <form method="post" asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Partida" class="control-label">Local de partida</label>
                    <input asp-for="Partida" class="form-control" />
                    <span asp-validation-for="Partida" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Chegada" class="control-label">Local de chegada</label>
                    <input asp-for="Chegada" class="form-control" />
                    <span asp-validation-for="Chegada" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Ida" class="control-label">Data de ida (dd/mm/aaaa)</label>
                    <input asp-for="Ida" class="form-control" />
                    <span asp-validation-for="Ida" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Volta" class="control-label">Data de volta (dd/mm/aaaa)</label>
                    <input asp-for="Volta" class="form-control" />
                    <span asp-validation-for="Volta" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Criar Destino" class="btn btn-warning" />
                </div>
            </form>
        </div>
    </div>
</div>

AtivMod3JoaoLucas/AtivMod3JoaoLucas/Views/Destino/EditarDestino.cshtml
@model AgenciaViagens.Models.Destino;

@{
    ViewData["Title"] = "Atualizar dados";
}

<br />
<br />
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <h3>Atualizar dados de destino</h3>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-sm-10">
            <form method="post" asp-action="EditarDestino">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Partida" class="control-label">Local de partida</label>
                    <input asp-for="Partida" class="form-control" />
                    <span asp-validation-for="Partida" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Chegada" class="control-label">Local de chegada</label>
                    <input asp-for="Chegada" class="form-control" />
                    <span asp-validation-for="Chegada" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Ida" class="control-label">Data de ida (dd/mm/aaaa)</label>
                    <input asp-for="Ida" class="form-control" />
                    <span asp-validation-for="Ida" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Volta" class="control-label">Data de volta (dd/mm/aaaa)</label>
                    <input asp-for="Volta" class="form-control" />
                    <span asp-validation-for="Volta" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Atualizar" class="btn btn-warning" />
                </div>
            </form>
        </div>
    </div>
</div>

AtivMod3JoaoLucas/AtivMod3JoaoLucas/Views/Destino/Index.cshtml
@model IEnumerable<AgenciaViagens.Models.Destino> 
    @{
        ViewData["Title"] = "Lista de Destinos";
}
<br />
<br />
                      <div class="container">
                          <div class="row">
                              <div class="col-sm-6">
                                  <h3>Lista de Destinos</h3>
                              </div>
                              <div class="col-sm-6">
                                  <a class="btn btn-warning d-block" asp-action="Create" asp-controller="Destino">Fazer nova viagem</a>
                              </div>
                          </div>
                          <br />
                          <br />

                          <div class="row">
                              @if (Model.Count() > 0)
                              {
                              <table class="table table-bordered table-striped">
                                  <thead>
                                      <tr>
                                          <td>@Html.DisplayNameFor(m => m.Id)</td>
                                          <td>@Html.DisplayNameFor(m => m.Partida)</td>
                                          <td>@Html.DisplayNameFor(m => m.Chegada)</td>
                                          <td>@Html.DisplayNameFor(m => m.Ida)</td>
                                          <td>@Html.DisplayNameFor(m => m.Volta)</td>
                                          <td>Ações</td>
                                      </tr>
                                  </thead>
                                  <tbody>
                                      @foreach (var item in Model)
                                      {
                                      <tr>
                                          <td>@item.Id</td>
                                          <td>@item.Partida</td>
                                          <td>@item.Chegada</td>
                                          <td>@item.Ida</td>
                                          <td>@item.Volta</td>
                                          <td>
                                              <a asp-action="EditarDestino" asp-route-id="@item.Id" class="btn text-danger">Editar</a>
                                              <a asp-action="DeletarDestino" asp-route-id="@item.Id" class="btn btn-danger">Deletar</a>
                                          </td>
                                      </tr>

                                      }
                                  </tbody>
                              </table>
                              }
                              else
                              {
                              <p>Sem registros.</p>
                              }
                          </div>
                      </div>

AtivMod3JoaoLucas/AtivMod3JoaoLucas/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<body>

    <div class="bg-home"><img src="https://i.imgur.com/CtyQuJv.jpg" alt="Second slide"></div>
    <div class="text-center">
        <div class="cover-container d-flex w-100 h-100 mx-auto flex-column p-5">

            <main role="main" class="inner cover">
                <img src="https://i.imgur.com/qBgy3ah.png" alt="Logo" style="width:280px;" />
                <h1 class="cover-heading text-light">Agência de viagens Nº1 do Brasil</h1>
                <p class="lead text-light">
                    Se você está procurando os melhores preços em passagens aéreas e hotéis temos opções incríveis para você!
                </p>

                <div class="container">
                    <div class="row">

                        <div class="col p-3">
                            <div class="card shadow" style="width: 100%;">
                                <img src="https://i.imgur.com/I0FUuXd.jpg" class="card-img-top" alt="...">
                                <div class="card-body">
                                    <h2 class="card-title">Rio de Janeiro</h2>
                                    <h5 class="card-title text-danger">Preço especial</h5>
                                    <p class="card-text">Rio de Janeiro (informalmente referida como Rio) é um município brasileiro, capital do estado homônimo, situado no Sudeste do país. Maior destino turístico internacional no Brasil.</p>
                                    <a asp-area="" asp-controller="Home" asp-action="Promocoes" class="btn btn-warning"><b>Ver pacotes</b></a>
                                </div>
                            </div>
                        </div>

                        <div class="col p-3">
                            <div class="card shadow" style="width: 100%;">
                                <img src="https://i.imgur.com/ii5kcvI.jpg" class="card-img-top" alt="...">
                                <div class="card-body">
                                    <h2 class="card-title">Maceió</h2>
                                    <h5 class="card-title text-danger">Preço especial</h5>
                                    <p class="card-text">Maceió é um município brasileiro, capital do estado de Alagoas, na Região Nordeste do país. As festividades realizadas na cidade anualmente atraem uma enorme quantidade de turistas.</p>
                                    <a asp-area="" asp-controller="Home" asp-action="Promocoes" class="btn btn-warning"><b>Ver pacotes</b></a>
                                </div>
                            </div>
                        </div>

                        <div class="col p-3">
                            <div class="card shadow" style="width: 100%;">
                                <img src="https://i.imgur.com/YiMnXlg.jpg" class="card-img-top" alt="...">
                                <div class="card-body">
                                    <h2 class="card-title">Foz do Iguaçu</h2>
                                    <h5 class="card-title text-danger">ÚLTIMAS RESERVAS</h5>
                                    <p class="card-text">Foz do Iguaçu é um município brasileiro localizado na Região Oeste estado do Paraná. Conhecida internacionalmente pelas Cataratas do Iguaçu, é uma das 7 Maravilhas da Natureza.</p>
                                    <a asp-area="" asp-controller="Home" asp-action="Promocoes" class="btn btn-warning"><b>Ver pacotes</b></a>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>

            </main>

            <section class="container pb-4 pt-4 mb-md-3">
                <div class="row">
                    <div class="col-md-8 mb-4">
                        <div class="d-sm-flex justify-content-between align-items-center bg-warning overflow-hidden rounded-3">
                            <div class="py-4 my-2 my-md-0 py-md-5 px-4 ms-md-3 text-center text-sm-start">
                                <h3 class="mb-2">
                                    <i class="bi bi-life-preserver" style="font-size: 60px"></i><br />
                                    Viaje em segurança!
                                </h3>
                                <h6 class="fs-lg fw-light mb-4">Proporcionamos o melhor sistema de segurança para que sua viajem saia conforme o planejado</h6>
                                <a class="btn btn-light btn-shadow" asp-area="" asp-controller="Destino" asp-action="Index">Faça sua viagem</a>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-4 mb-4">
                        <div class="d-flex flex-column h-100 justify-content-center bg-dark bg-position-center rounded-3">
                            <div class="py-4 my-2 px-4 text-center">
                                <div class="py-1">
                                    <h5 class="mb-2 text-light">
                                        <i class="bi bi-credit-card" style="font-size: 60px"></i><br />
                                        Destinos inesquecíveis
                                    </h5>
                                    <p class="fs-sm text-light">E com as melhores formas de pagamento</p>
                                    <a class="btn btn-light btn-shadow" asp-area="" asp-controller="Destino" asp-action="Index">Faça sua viagem</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>


        </div>
    </div>

</body>

<style>
    .bg-home img {
        width: 100%;
        height: 450px;
        object-fit: cover;
        z-index: -2;
        position: absolute;
    }
    .bg-home::after {
        display: block;
        content: "";
        width: 100%;
        height: 450px;
        background-color: #000;
        z-index: -1;
        position: absolute;
        opacity: .3;
    }

    body {
        background-color: #f1f1f1;
    }
</style>

AtivMod3JoaoLucas/AtivMod3JoaoLucas/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Agência Viagens</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
</head>
<body>
    <header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm bg-warning">
                <div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="https://i.imgur.com/ojUOGOW.png" alt="Logo" style="width:100px;" /></a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">
                                    <b>
                                        <i class="bi bi-house"></i>
                                        Home
                                    </b>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Destino" asp-action="Index">
                                    <b>
                                        <i class="bi bi-signpost-split"></i>
                                        Destinos
                                    </b>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Promocoes">
                                    <b>
                                        <i class="bi bi-star"></i>
                                        Promoções
                                    </b>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Contato">
                                    <b>
                                        <i class="bi bi-chat-left-text"></i>
                                        Contato
                                    </b>
                                </a>
                            </li>
                        </ul>
                        <ul class="navbar-nav flex-grow-1 justify-content-end">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Conta" asp-action="Index">
                                    <b>
                                        <i class="bi bi-person"></i>
                                        Sua Conta
                                    </b>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
    </header>

    <div>
        <main role="main">
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-muted">
        <div class="container">
            &copy; 2021 - Agência Viagens - desenvolvido por João Lucas | <a asp-area="" asp-controller="Home" asp-action="Contato">Contato</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>